name: tests

on: [pull_request, push]

env:
  FORCE_COLOR: 2

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['lts/*', 18]
        package-manager: ['npm', 'pnpm', 'yarn']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install pnpm
        if: ${{ matrix.package-manager == 'pnpm' }}
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies via yarn
        if: ${{ matrix.package-manager == 'yarn' }}
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
          useYarn: true
          install-command: yarn install
      - name: Install dependencies
        if: ${{ matrix.package-manager != 'yarn' }}
        run: ${{ matrix.package-manager }} install
      - run: ${{ matrix.package-manager }} run test
      - uses: codecov/codecov-action@v3
        if: ${{ github.event_name == 'pull_request' }}
        with:
          flags: ${{ matrix.os }}-${{ matrix.node }}

  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' && contains(github.head_ref, 'dependabot/github_actions') }}
        with:
          github-token: ${{ secrets.github_token }}
