name: tests

on: [pull_request, push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 12]

    steps:
    - name: Set git to use LF
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - uses: actions/checkout@v2.3.4
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2.3.0
      with:
        node-version: ${{ matrix.node }}
    - run: npm i
    - run: npm test
    - run: npm run lcov
    - uses: codecov/codecov-action@v2.0.2
      if: ${{ github.event_name == 'pull_request' }}
      with:
        flags: ${{ matrix.os }}-${{ matrix.node }}

  automerge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.2.0
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' && contains(github.head_ref, 'dependabot/github_actions') }}
        with:
          github-token: ${{secrets.github_token}}
