name: tests

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

env:
  FORCE_COLOR: 2

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Use Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: package.json
          package-manager-cache: false
      - run: npm install --ignore-scripts
      - run: npm run check

  test:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: ['22', '24', '26']

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v7
        with:
          node-version: ${{ matrix.node }}
          package-manager-cache: false
      - run: npm install --ignore-scripts
      - run: npm run test:node-test
      - uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4 # v7
        if: ${{ github.event_name == 'pull_request' }}
        with:
          flags: ${{ matrix.os }}-${{ matrix.node }}

  automerge:
    needs: [lint, test]
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/github_actions/actions/') }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Merge first-party GitHub Actions Dependabot PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge "$PR_URL" --squash --delete-branch
